import "./globals.css";
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: "Oboticario",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
        <Analytics/>
      </body>
    </html>
  );
}
